DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS pet;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE pet (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  type TEXT NOT NULL,
  breed TEXT NOT NULL,
  description TEXT NOT NULL,
  hobbies TEXT NOT NULL
);